### PR TITLE
keyprovider: Upgraded tonic and prost version

### PR DESCRIPTION
**Pull request by pravinrajr9**
Signed-off-by: R, Praveenraj <praveenraj.r@intel.com>

### CODE REVIEW

**Comment by pravinrajr9** [comment]
fmt check is failing for autogenerated code, Should I comment the src/utils/keyprovider.rs protobuf generation again in build.rs? and push the indented one?

**Comment by arronwy** [comment]
> fmt check is failing for autogenerated code, Should I comment the src/utils/keyprovider.rs protobuf generation again in build.rs? and push the indented one?

Thanks @pravinrajr9 .
tonic-build switched to use prettyplease to format output: https://github.com/hyperium/tonic/commit/d6c0fc112b2288a080fd0a727453b24d666e3d79

We may can use `#[rustfmt::skip]` to skip the generated keyprovider module in utils, @sameo any suggestions?

BTW, we can also combine this two commits into one.

**Comment by sameo** [comment]
> We may can use `#[rustfmt::skip]` to skip the generated keyprovider module in utils, @sameo any suggestions?

Yes, that sounds reasonable to me

**Review by arronwy — APPROVED** [review]
Thanks @pravinrajr9 , lgtm

**Review by sameo — APPROVED** [review]

**Pull request merged**
